//FETCH BOARDS
export const FETCH_BOARDS_REQUEST = "FETCH_BOARDS_REQUEST";
export const FETCH_BOARDS_SUCCESS = "FETCH_BOARDS_SUCCESS";
export const FETCH_BOARDS_FAILURE = "FETCH_BOARDS_FAILURE";

//CREATE NEW BOARD
export const CREATE_BOARDS_REQUEST = "CREATE_BOARDS_REQUEST";
export const CREATE_BOARDS_SUCCESS = "CREATE_BOARDS_SUCCESS";
export const CREATE_BOARDS_FAILURE = "CREATE_BOARDS_FAILURE";

//DELETE BOARD
export const DELETE_BOARDS_REQUEST = "DELETE_BOARDS_REQUEST";
export const DELETE_BOARDS_SUCCESS = "DELETE_BOARDS_SUCCESS";
export const DELETE_BOARDS_FAILURE = "DELETE_BOARDS_FAILURE";

//UPDATE BOARD
export const UPDATE_BOARDS_REQUEST = "UPDATE_BOARDS_REQUEST";
export const UPDATE_BOARDS_SUCCESS = "UPDATE_BOARDS_SUCCESS";
export const UPDATE_BOARDS_FAILURE = "UPDATE_BOARDS_FAILURE";
